# Generated by Django 5.1.7 on 2025-03-19 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_pais', '0001_initial'),
        ('app_tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantidade', models.IntegerField(default=0)),
                ('quantidade_extra', models.IntegerField(default=0)),
                ('quantidade_troca', models.IntegerField(default=0)),
                ('quantidade_cunhagem', models.IntegerField(default=0)),
                ('fao', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto_frente', models.FileField(blank=True, default=None, null=True, upload_to='imagens/moedas')),
                ('foto_verso', models.FileField(blank=True, default=None, null=True, upload_to='imagens/moedas')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pais.pais')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tipo.tipo')),
            ],
        ),
    ]
