# Generated by Django 5.1.7 on 2025-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_moeda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='comemorativas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='foto_frente',
            field=models.FileField(blank=True, default=None, null=True, upload_to='moedas'),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='foto_verso',
            field=models.FileField(blank=True, default=None, null=True, upload_to='moedas'),
        ),
    ]
