# Generated by Django 5.1.7 on 2025-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_moeda', '0002_moeda_comemorativas_alter_moeda_foto_frente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='comemorativas',
            field=models.CharField(default='', max_length=50),
        ),
    ]
